---

- name: Check cosi-server directory
  become: true
  file:
      path: "{{ cosi_directory }}"
      owner: "{{ cosi_owner }}"
      group: "{{ cosi_group }}"
      mode: 0755
      state: directory

- name: Download cosi-server release file
  become: true
  get_url:
      url: "{{ download_url }}"
      dest: "{{ download_file }}"
      checksum: "{{ version_checksum }}"

- name: Unpack cosi-server release
  become: true
  unarchive:
      remote_src: true
      src: "{{ download_file }}"
      dest: "{{ cosi_directory }}"
      owner: "{{ cosi_owner }}"
      group: "{{ cosi_group }}"
  notify: Restart Server

- name: Install cosi-server config
  become: true
  template:
      src: cosi-server.yaml.j2
      dest: "{{ cosi_directory }}/etc/cosi-server.yaml"
      owner: "{{ cosi_owner }}"
      group: "{{ cosi_group }}"
      mode: 0644
  notify: Restart Server

#
# Systemd
#
- name: Install cosi-server service (systemd)
  become: true
  when: ansible_facts['service_mgr'] == "systemd"
  template: 
      src: circonus-cosi-server.service.j2 
      dest: /etc/systemd/system/circonus-cosi-server.service
      owner: "root"
      group: "root"
      mode: 0644
  notify: Restart Server

- name: Check cosi-server local packages directory
  become: true
  when: local_agent_packages
  file:
      path: "{{ cosi_directory }}/content/packages"
      owner: "{{ cosi_owner }}"
      group: "{{ cosi_group }}"
      mode: 0755
      state: directory
#
# rsync - used for agent package synchronize below
#
- name: Install rsync command
  become: true
  package:
      name: rsync
      state: present

- name: Upload cosi-agent packages
  become: true
  when: local_agent_packages
  synchronize:
      src: "roles/server/files/packages"
      dest: "{{ cosi_directory }}/content"
      rsync_opts:
          - "--exclude=index.html"
  # copy:
  #     src: "{{ item }}"
  #     dest: "{{ cosi_directory }}/content/packages"
  #     owner: "{{ cosi_owner }}"
  #     group: "{{ cosi_group }}"
  #     mode: 0644
  # with_fileglob:
  #     - "packages/*{{ agent_version|replace('v','') }}*"

- name: Ensure release index accessible by cosi-server user
  become: true
  when: local_agent_packages
  file:
      path: "{{ cosi_directory }}/content/packages/index.html"
      owner: nobody
      group: nobody
      mode: 0644
      state: touch

- name: Install custom package configuration
  become: true
  template:
    src: circonus-packages.yaml.j2
    dest: "{{ cosi_directory }}/etc/circonus-packages.yaml"
    owner: "{{ cosi_owner }}"
    group: "{{ cosi_group }}"
    mode: 0644
  notify: Restart Server
