---

#
# This is mainly here as a stub - there are not currently any OS specific tasks
#

- debug: msg="OS {{ ansible_os_family }} {{ ansible_distribution }} v{{ ansible_distribution_version }} {{ ansible_userspace_architecture }}"

- name: Common variables
  include_vars: "../vars/common.yaml"

- name: Common tasks
  import_tasks: "common.yaml"

- name: OS Specific variables
  include_vars: "{{ item }}"
  with_first_found:
      - files:
          - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
          - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
          - "../vars/{{ ansible_distribution }}.yaml"
          - "../vars/{{ ansible_os_family }}.yaml"
          - "../vars/{{ ansible_system }}.yaml"
        skip: true

- name: OS Specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
      - files:
          - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
          - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
          - "{{ ansible_distribution }}.yaml"
          - "{{ ansible_os_family }}.yaml"
          - "{{ ansible_system }}.yaml"
        skip: true
