---
    # rename to 'config.yaml', edit and set variables

    # set server ip and server port to correspond with the private ip
    # and port set in ../../server/Vagrantfile
    # NOTE: the server NEEDS to be running for examples to work correctly
    server_ip: 192.168.100.10
    server_port: 8080

    # set to the api key from a valid new host cosi command as displayed in the UI
    circonus_api_key: null

    # set to the api app from a valid new host cosi command as displayed in the UI
    circonus_api_app: null
