# rubocop:disable Metrics/BlockLength

require 'yaml'

config_file = "#{File.dirname(__FILE__)}/config.yaml"

unless File.file? config_file
    puts 'missing config file - see examples-config.yaml'
    exit 1
end

cfg = YAML.load_file(config_file)

svr_ip = cfg['server_ip']
if [nil, ''].include? svr_ip
    puts 'invalid server ip in config.yaml'
    exit 1
end
svr_port = cfg['server_port']
if [nil, 0].include? svr_port
    puts 'invalid server port in config.yaml'
    exit 1
end
api_key = cfg['circonus_api_key']
if [nil, ''].include? api_key
    puts 'invalid api key in config.yaml'
    exit 1
end
api_app = cfg['circonus_api_app']
if [nil, ''].include? api_app
    puts 'invalid api app in config.yaml'
    exit 1
end

cosi_url = "http://#{svr_ip}:#{svr_port}/"
cosi_cmd = %(
curl -sSL \"#{cosi_url}install/\" | bash -s -- \
--key \"#{api_key}\" \
--app \"#{api_app}\" \
--cosiurl \"#{cosi_url}\"
)

#
# NOTE: private_network IP addresses must be in same subnet
#       as the example server's IP (server_ip in config.yaml).
#

Vagrant.configure(2) do |config|
    #
    # RHEL - CentOS
    #
    config.vm.define 'c7', autostart: false do |c7|
        c7.vm.box = 'maier/centos-7.5.1804-x86_64'
        c7.vm.hostname = 'cosi-tool-c7'
        c7.vm.network 'private_network', ip: '192.168.100.12'
        c7.vm.provider 'virtualbox' do |vb|
            vb.name = 'c7_cosi-examples-client-basic'
            vb.cpus = 1
        end
        c7.vm.provision 'shell', inline: <<-SHELL
            yum -q -e 0 makecache fast
            #{cosi_cmd}
        SHELL
    end

    config.vm.define 'c6', autostart: false do |c6|
        c6.vm.box = 'maier/centos-6.8-x86_64'
        c6.vm.hostname = 'cosi-tool-c6'
        c6.vm.network 'private_network', ip: '192.168.100.11'
        c6.vm.provider 'virtualbox' do |vb|
            vb.name = 'c6_cosi-examples-client-basic'
            vb.cpus = 1
        end
        c6.vm.provision 'shell', inline: <<-SHELL
            yum -q -e 0 makecache fast
            #{cosi_cmd}
        SHELL
    end

    #
    # Ubuntu
    #
    config.vm.define 'u18', autostart: false do |u18|
        u18.vm.box = 'maier/ubuntu-18.04-x86_64'
        u18.vm.hostname = 'cosi-tool-u18'
        u18.vm.network 'private_network', ip: '192.168.100.23'
        u18.vm.provider 'virtualbox' do |vb|
            vb.name = 'u18_cosi-examples-client-basic'
            vb.cpus = 1
        end
        u18.vm.provision 'shell', inline: <<-SHELL
            yum -q -e 0 makecache fast
            #{cosi_cmd}
        SHELL
    end

    config.vm.define 'u16', autostart: false do |u16|
        u16.vm.box = 'maier/ubuntu-16.04-x86_64'
        u16.vm.hostname = 'cosi-tool-u16'
        u16.vm.network 'private_network', ip: '192.168.100.22'
        u16.vm.provider 'virtualbox' do |vb|
            vb.name = 'u16_cosi-examples-client-basic'
            vb.cpus = 1
        end
        u16.vm.provision 'shell', inline: <<-SHELL
            yum -q -e 0 makecache fast
            #{cosi_cmd}
        SHELL
    end

    config.vm.define 'u14', autostart: false do |u14|
        u14.vm.box = 'maier/ubuntu-14.04-x86_64'
        u14.vm.hostname = 'cosi-tool-u14'
        u14.vm.network 'private_network', ip: '192.168.100.21'
        u14.vm.provider 'virtualbox' do |vb|
            vb.name = 'u14_cosi-examples-client-basic'
            vb.cpus = 1
        end
        u14.vm.provision 'shell', inline: <<-SHELL
            yum -q -e 0 makecache fast
            #{cosi_cmd}
        SHELL
    end
end
