---
- hosts: all
  gather_facts: true
  vars:
    # what port should the cosi-server daemon listen on
    # NOTE: cosi-server runs as nobody...a user which cannot listen on ports below 1024
    cosi_server_port: 8080
    #
    # cosi-server repository URL (only change if testing development version of cosi-server)
    #
    repo_url: "https://github.com/maier/cosi-server"
    #
    # set to cosi-server tag for release version to install (see <repo_url>/releases)
    # get version checksum from cosi-server_checksums.txt (sha256 signatures) in <repo_url>/releases
    #
    version_tag: "v0.2.1"
    version_checksum: sha256:11868fceb364bb794d51b84883886bb5ecf22c46a16da3c3bfcbc05d2802ef51
    #
    # derived name of tgz to download and install
    #
    install_file: "cosi-server_{{ version_tag|replace('v','') }}_{{ ansible_system|lower }}_64-bit.tar.gz"
    #
    # the full download URL computed for the release would be, for example:
    # https://github.com/circonus-labs/cosi-server/releases/download/v0.1.0/cosi-server_0.1.0_linux_64-bit.tar.gz
    #
    download_url: "{{ repo_url }}/releases/download/{{ version_tag }}/{{ install_file }}"
    #
    # set to true to serve agent packages from local cosi-sever (e.g. during dev testing)
    # put the test packages to serve in roles/server/files/packages directory
    # and ensure roles/server/templates/circonus-packages.yaml.j2 reflects the test package names
    #
    local_agent_packages: true
    #
    # cosi tool settings - the file to redirect the install request to will be
    # dynamically generated based on query arguments sent by the installer (system
    # os type (e.g. linux, freebsd, solaris, etc.), system architecture, etc.)
    cosi_tool_version: v0.2.2
    cosi_tool_base_url: "https://github.com/maier/cosi-tool/releases/download"
  roles:
    - os
    - server
